M48
; DRILL file {KiCad 7.0.10} date Thu Jul 25 14:37:49 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-25T14:37:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X2.015Y-4.9
X2.015Y-5.375
T2
X2.4091Y-1.9994
X2.6Y-1.9994
T3
X2.3972Y-1.8801
X2.6118Y-1.8801
M30
