M48
; DRILL file {KiCad 7.0.10} date Thu Jul 25 15:06:30 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-25T15:06:30-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X3.84Y-4.9
X3.84Y-5.375
T2
X4.2341Y-1.9994
X4.425Y-1.9994
T3
X4.2222Y-1.8801
X4.4368Y-1.8801
M30
